### PR TITLE
I1 transfer to ZAE should automatically demote to C1

### PR DESCRIPTION
**Pull request by catcarbon**

### CODE REVIEW

**Comment by mkosmo** [comment]
What if their previous rating was a C3?

**Comment by catcarbon** [comment]
> There needs to be a check for previous promotion to C3; if so, that should be the new rating.

I identified several users who are I1 but have no promotion records at all. What's the supposed behavior for this case?

**Comment by bnahin** [comment]
C1 if no records exist which is rare.

**Comment by bnahin** [comment]
Please also add the removal of their MTR role

**Comment by bnahin** [comment]
While you're at it, please also remove MTR role when being promoted to I1 or I3.

**Pull request merged**
